# Generated by Django 5.1.2 on 2024-11-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0002_rename_estado_ticket_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='secuencia',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
